Python3 support. (C)
vadimkantorov/caffemodel2pytorch pull request #7
Opened 2019-03-27 11:17 UTC by sebftw

Continued from https://github.com/vadimkantorov/caffemodel2pytorch/pull/6.

2019-03-27 13:39 UTC, vadimkantorov requested changes

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +from urllib.request import urlopen
To support both py2 and py3 this could be:
```
try:

	from urllib.request import urlopen
except:
	from urllib2 import urlopen
```

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			module_constructor = ([v for k, v in list(modules.items()) if k.replace('_', '').upper() in [layer_type.replace('_', '').upper(), layer.name.replace('_', '').upper()]] + [None])[0]
This change is unneccessary I think.

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +				print(('Skipping layer [{}, {}, {}]: not found in caffemodel2pytorch.modules dict'.format(layer.name, layer_type, layer.type)))
Brackets change is unneccessary

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		numpy = not all(isinstance(v, torch.autograd.Variable) for v in list(variables.values()))
`not all(map(torch.is_tensor, variables.values()))` - after a merge of tensors and variables, this should do

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		variables = {k : convert_to_gpu_if_enabled(torch.autograd.Variable(torch.from_numpy(v.copy())) if numpy else v) for k, v in list(variables.items())}
`variables = {k : convert_to_gpu_if_enabled(torch.from_numpy(v.copy()) if numpy else v) for k, v in variables.items()}` - list call is unnecessary, explicit Variable call is also unnecessary in modern pytorch

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			variables.update(dict(list(zip(module.caffe_output_variable_names, outputs))))
I think list call is also unnecessary here

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		self.blobs.update({k : Blob(data = v, numpy = numpy) for k, v in list(variables.items())})
list call is unnecessary

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		return {k : v.detach().cpu().numpy() if numpy else v for k, v in list(variables.items()) if k in caffe_output_variable_names}
list call is unnecessary

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			for k, v in list(h5py.File(weights, 'r').items()):
unnecessary list call

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			print(('caffemodel2pytorch: loaded model from [{}] in HDF5 format'.format(weights)))
Unnecessary extra brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			print(('caffemodel2pytorch: loading model from [{}] in HDF5 format failed [{}], falling back to caffemodel format'.format(weights, e.message)))
Unnecessary extra brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +				print(('caffemodel2pytorch: loading model from [{}] in caffemodel format, WARNING: file length [{}] is not equal to number of parsed bytes [{}]'.format(weights, len(bytes_weights), bytes_parsed))
Unnecessary extra brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			print(('caffemodel2pytorch: loaded model from [{}] in caffemodel format'.format(weights)))
more brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			for k, v in list(self.state_dict().items()):
unnecessary list

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		print(('caffemodel2pytorch: saved model to [{}] in HDF5 format'.format(weights)))
brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +				outputs = [kv for kv in list(self.net(**inputs).items()) if self.net.blob_loss_weights[kv[0]] != 0]
unnecessary list call

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			print(('{}] Iteration {}, loss: {}'.format(log_prefix, self.iter, loss_batch)))
brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +				print(('{}]     Train net output #{}: {} = {} (* {} = {} loss)'.format(log_prefix, i, name, loss, self.net.blob_loss_weights[name], self.net.blob_loss_weights[name] * loss)))
brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			print(('{}] Iteration {}, lr = {}, time = {}'.format(log_prefix, self.iter, self.optimizer_params['lr'], time.time() - tic)))
brackets

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +			h.update(**{k : numpy.array(blob['data'], dtype = numpy.float32).reshape(*blob['shape']) for k, blob in list(blobs.items())})
unnecessary list call

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		(numpy.savez if args.output_path[-1] == 'z' else numpy.save)(args.output_path, **{k : numpy.array(blob['data'], dtype = numpy.float32).reshape(*blob['shape']) for k, blob in list(blobs.items())})
unnecessary list call

2019-03-27 13:39 UTC, vadimkantorov commented on caffemodel2pytorch.py
> +		torch.save({k : torch.FloatTensor(blob['data']).view(*blob['shape']) for k, blob in list(blobs.items())}, args.output_path)
unnecesary list call

2019-03-27 14:50 UTC, sebftw commented
Awesome. I can try running it in about an hour. All the changes makes me wonder if 2to3 actually did anything necessary, haha.

2019-03-27 15:37 UTC, vadimkantorov commented
I don't think it did anything useful :) The only thing should have been the urlopen-related line

2019-03-28 11:23 UTC, sebftw reviewed
All the changes seem reasonable, so I added them in https://github.com/vadimkantorov/caffemodel2pytorch/pull/7/commits/4968ed72a7fbbb659a192309d9cfaa4c71768ecc.

2019-03-31 10:30 UTC, merged